version: '2'
services:
  database:
    image: postgres
    env_file:
      - .postgres.env
    ports:
      - "5432:5432"
  opennms:
    image: indigo/docker-opennms
    env_file:
      - .opennms.env
      - .postgres.env
    depends_on:
      - database
    command: ["-s"]
    ports:
      - "8980:8980"
      - "18980:18980"
      - "1099:1099"
      - "8101:8101"
      - "61616:61616"
      - "5817:5817"
      - "162:162/udp"
