version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432/tcp
  opennms:
    build:
      context: /
      args:
        var1: -i
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OPENNMS_DBUSER=opennms
      - OPENNMS_DBPASS=opennms
      - OPENNMS_HOME=/opt/opennms
      - OPENNMS_DB_CONFIG=${OPENNMS_HOME}/etc/opennms-datasources.xml
    expose:
      - 8980/tcp
    depends_on:
      - db
    links:
      - db:database