version: '2'
services:
  db_data:
    image: tianon/true
    volumes:
        - /var/lib/postgresql/data
  database:
    image: postgres
    env_file:
      - .postgres.env
    ports:
      - "5432:5432"
    depends_on:
      - db_data
    volumes_from:
      - db_data:rw
  opennms_data:
    image: tianon/true
    volumes:
        - /var/log/opennms
        - /var/opennms/rrd
        - /var/opennms/reports
        - /Users/indigo/test:/opt/opennms/etc
  opennms:
    image: indigo/docker-opennms:latest
    env_file:
      - .opennms.env
      - .postgres.env
    depends_on:
      - database
      - opennms_data
    volumes_from:
      - opennms_data:rw
    command: ["-f"]
    ports:
      - "8980:8980"
      - "18980:18980"
      - "1099:1099"
      - "8101:8101"
      - "61616:61616"
      - "5817:5817"
      - "162:162/udp"
  elastic1:
    image: elasticsearch:latest
    command: elasticsearch -Des.cluster.name="onmsTestCluster" -Des.node.name="Node-1" 
    ports:
      - "9200:9200"
      - "9300:9300"
  elastic2:
    image: elasticsearch:latest
    command: elasticsearch -Des.cluster.name="onmsTestCluster" -Des.node.name="Node-2" 
    ports:
      - "9201:9200"
      - "9301:9300"
  elastic3:
    image: elasticsearch:latest
    command: elasticsearch -Des.cluster.name="onmsTestCluster" -Des.node.name="Node-3" 
    ports:
      - "9202:9200"
      - "9302:9300"
  elastic4:
    image: elasticsearch:latest
    command: elasticsearch -Des.cluster.name="onmsTestCluster" -Des.node.name="Node-4" 
    ports:
      - "9203:9200"
      - "9303:9300"
